# This is a basic workflow to help you get started with Actions

name: Hello World Workflow

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: hello world action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Tom Dup'
